<?php
/**
 * Copyright © Two.inc All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /* @var \Two\Gateway\Block\Adminhtml\Order\View $block */ ?>
<?php if ($block->getMethod() == \Two\Gateway\Model\Two::CODE): ?>
    <?php $productName = $block->getProductName(); ?>
    <section class="admin__page-section order-view-account-information">
        <div class="admin__page-section-title">
            <span class="title"><?= $block->escapeHtml(__('%1 details', $productName)) ?></span>
        </div>
        <div class="admin__page-section-content">
            <div>
                <table width="100%">
                    <?php $fulfillments = $block->getTwoOrderFulfillments(); ?>
                    <?php if (!empty($fulfillments['fulfilled_orders'])): ?>
                        <tr>
                            <td>
                                <strong><?= $block->escapeHtml(__('Invoice')); ?></strong>
                            </td>
                            <td>
                                <?php foreach ($fulfillments['fulfilled_orders'] ?? [] as $fulfilled_order) { ?>
                                <a href="<?= $block->escapeHtml($fulfilled_order['invoice_url']); ?>" target="_blank">
                                    <?= $block->escapeHtml(__('Download')); ?></a>
                                <?php } ?>
                            </td>
                        </tr>
                    <?php endif; ?>
                    <?php if (!empty($fulfillments['refunds'])): ?>
                        <tr>
                            <td>
                                <strong><?= $block->escapeHtml(__('Credit note')); ?></strong>
                            </td>
                            <td>
                                <?php foreach ($fulfillments['refunds'] ?? [] as $refund) { ?>
                                <a href="<?= $block->escapeHtml($refund['credit_note_url']); ?>" target="_blank">
                                    <?= $block->escapeHtml(__('Download')); ?></a>
                                <?php } ?>
                            </td>
                        </tr>
                    <?php endif; ?>
                </table>
            </div>
        </div>
    </section>
<?php endif; ?>
