<?php
/**
 * Copyright © Two.inc All rights reserved.
 * See COPYING.txt for license details.
 */

use Two\Gateway\Block\Adminhtml\System\Config\Button\ErrorCheck;

/**
 * @see \Two\Gateway\Block\Adminhtml\System\Config\Button\ErrorCheck
 * @var ErrorCheck $block
 */
?>
<div id="two-result_error-modal"
     data-two-endpoind-url="<?= $block->escapeUrl($block->getErrorCheckUrl()) ?>">
    <div id="two-result_error">
        <div class="result"></div>
    </div>
</div>
<?= $block->getButtonHtml() ?>
